services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  worldpress:
    build: ./requirements/worldpress
    volumes:
      - worldpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb

  ngnix:
    build: ./requirements/ngnix
    networks:
      - inception
    ports:
      - "433:433"


volumes:
  mariadb:
  worldpress:

networks:
  inception:
    driver: bridge
