services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  # worldpress:
  #   build: ./requirements/worldpress
  #   volumes:
  #     - /home/nduvoid/data:/worldpress
  #   networks:
  #     - inception

  # ngnix:
  #   build: ./requirements/ngnix
  #   networks:
  #     - inception
  #   ports:
  #     - "80:80"


volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/nduvoid/data/mariadb
  worldpress:

networks:
  inception:
    driver: bridge
