services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - /home/nduvoid/data:/mariadb
    networks:
      - inception

  ngnix:
    build: ./requirements/ngnix
    networks:
      - inception
    ports:
      - "80:80"

  worldpress:
    build: ./requirements/worldpress
    volumes:
      - /home/nduvoid/data:/worldpress
    networks:
      - inception

volumes:
  mariadb:
  worldpress:

networks:
  inception:
    driver: bridge
